#!/bin/sh
set -e

# Directory where the built web app is served
HTML_DIR="/usr/share/nginx/html"

# JavaScript escape function to safely escape strings for JSON/JS
# Escapes quotes, backslashes, and newlines to prevent injection
js_escape() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/$/\\n/' | tr -d '\n' | sed 's/\\n$//'
}

# Create the env-config.js file with environment variables
# Includes ALL fields expected by the client env schema in env.js
cat > "${HTML_DIR}/env-config.js" << EOF
// Runtime environment configuration - generated by docker-entrypoint.sh
// This file is generated at container startup and injects environment variables
window.__ENV__ = {
  APP_ENV: "$(js_escape "${APP_ENV:-production}")",
  NAME: "$(js_escape "${IC_NAME:-Resgrid IC}")",
  SCHEME: "$(js_escape "${IC_SCHEME:-ResgridIC}")",
  BUNDLE_ID: "$(js_escape "${IC_BUNDLE_ID:-com.resgrid.command}")",
  PACKAGE: "$(js_escape "${IC_PACKAGE:-com.resgrid.command}")",
  VERSION: "$(js_escape "${IC_VERSION:-0.0.1}")",
  ANDROID_VERSION_CODE: 1,
  BASE_API_URL: "$(js_escape "${IC_BASE_API_URL:-https://api.resgrid.com}")",
  API_VERSION: "$(js_escape "${IC_API_VERSION:-v4}")",
  RESGRID_API_URL: "$(js_escape "${IC_RESGRID_API_URL:-/api/v4}")",
  CHANNEL_HUB_NAME: "$(js_escape "${IC_CHANNEL_HUB_NAME:-eventingHub}")",
  REALTIME_GEO_HUB_NAME: "$(js_escape "${IC_REALTIME_GEO_HUB_NAME:-geolocationHub}")",
  LOGGING_KEY: "$(js_escape "${IC_LOGGING_KEY:-}")",
  APP_KEY: "$(js_escape "${IC_APP_KEY:-}")",
  IC_MAPBOX_PUBKEY: "$(js_escape "${IC_MAPBOX_PUBKEY:-}")",
  IS_MOBILE_APP: "false",
  SENTRY_DSN: "$(js_escape "${IC_SENTRY_DSN:-}")",
  COUNTLY_APP_KEY: "$(js_escape "${IC_COUNTLY_APP_KEY:-}")",
  COUNTLY_SERVER_URL: "$(js_escape "${IC_COUNTLY_SERVER_URL:-}")"
};
EOF

echo "Generated env-config.js with runtime environment variables"

# Check if index.html exists
if [ ! -f "${HTML_DIR}/index.html" ]; then
  echo "Error: index.html not found in ${HTML_DIR}"
  exit 1
fi

# Inject the env-config.js script into index.html if not already present
if ! grep -q "env-config.js" "${HTML_DIR}/index.html"; then
  # Insert script tag right after the opening <head> tag
  sed -i 's|<head>|<head>\n    <script src="/env-config.js"></script>|' "${HTML_DIR}/index.html"
  echo "Injected env-config.js script tag into index.html"
else
  echo "env-config.js already present in index.html"
fi

echo "Starting nginx..."

# Execute the CMD (nginx)
exec "$@"
